config:
  credentials: []
  project_repos:
    code-repo.d4science.org/MaDgIK/uoa-repository-manager-ui:
      branch: master
      repo: https://code-repo.d4science.org/MaDgIK/uoa-repository-manager-ui.git
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: fix/updatego
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      code-repo.d4science.org/MaDgIK/uoa-repository-manager-ui git:
        commands:
        - /usr/bin/env sh .sqa/script.persimmon_optimistic_gull.sh
        container: qc.acc_cerulean_joyful_fox
  QC.Doc:
    repos:
      code-repo.d4science.org/MaDgIK/uoa-repository-manager-ui find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.marigold_understanding_tortoise.sh
        container: qc.doc_clove_shrewd_jaguar
      code-repo.d4science.org/MaDgIK/uoa-repository-manager-ui git:
        commands:
        - /usr/bin/env sh .sqa/script.rust_unique_lionfish.sh
        container: qc.doc_sapphire_outgoing_dragonfly
      code-repo.d4science.org/MaDgIK/uoa-repository-manager-ui markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.lavender_cheerful_cassowary.sh
        container: qc.doc_carmine_curious_reindeer
  QC.Lic:
    repos:
      code-repo.d4science.org/MaDgIK/uoa-repository-manager-ui licensee:
        commands:
        - /usr/bin/env sh .sqa/script.turmeric_inventive_turkey.sh
        container: qc.lic_polar_imaginative_bat
  QC.Sty:
    repos:
      code-repo.d4science.org/MaDgIK/uoa-repository-manager-ui jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.beige_clever_quail.sh
        container: qc.sty_pink_industrious_pegasus
  QC.Ver:
    repos:
      code-repo.d4science.org/MaDgIK/uoa-repository-manager-ui get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.frost_proactive_viper.sh
        container: qc.ver_peony_lucky_spren
timeout: 5400
