config:
  credentials: []
  project_repos:
    code-repo.d4science.org/MaDgIK/uoa-repository-manager-ui:
      branch: master
      repo: https://code-repo.d4science.org/MaDgIK/uoa-repository-manager-ui.git
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      code-repo.d4science.org/MaDgIK/uoa-repository-manager-ui git:
        commands:
        - /usr/bin/env sh .sqa/script.baggy-crimson-seal.sh
        container: qc.acc_droopy-firebrick-goat
  QC.Doc:
    repos:
      code-repo.d4science.org/MaDgIK/uoa-repository-manager-ui find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.messy-cornflower-impala.sh
        container: qc.doc_nippy-orchid-dolphin
      code-repo.d4science.org/MaDgIK/uoa-repository-manager-ui git:
        commands:
        - /usr/bin/env sh .sqa/script.grumpy-linen-crab.sh
        container: qc.doc_lousy-brass-crab
      code-repo.d4science.org/MaDgIK/uoa-repository-manager-ui markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.messy-champagne-anteater.sh
        container: qc.doc_snappy-sepia-chicken
  QC.Lic:
    repos:
      code-repo.d4science.org/MaDgIK/uoa-repository-manager-ui licensee:
        commands:
        - /usr/bin/env sh .sqa/script.scaly-amber-frise.sh
        container: qc.lic_tasty-periwinkle-woodpecker
  QC.Sty:
    repos:
      code-repo.d4science.org/MaDgIK/uoa-repository-manager-ui jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.scanty-tan-whale.sh
        container: qc.sty_randy-pink-mandrill
  QC.Ver:
    repos:
      code-repo.d4science.org/MaDgIK/uoa-repository-manager-ui get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.greasy-lavender-swan.sh
        container: qc.ver_slimy-denim-frise
timeout: 5400
